token: ""

guild_id: 123456789

base_voice: "Voice"

owner_id: 164546159140929538

discord_bots_key: 123456

postgres_credentials:
    host: "postgres-db"
    user: "yinbotuser"
    database: "yinbotdb"
    password: "yinbot-password"
